GET http://localhost:3000/api/users
###

DELETE http://localhost:3000/api/articles?id=1
###

GET http://localhost:3000/api/articles/?id=1,2,3,4&orderBy=id&ordered=desc
###

DELETE http://localhost:3000/api/articles/2